// <auto-generated />
using System;
using LibraryAutomation1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAutomation1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250621103627_AddIsActiveColumnToMember")]
    partial class AddIsActiveColumnToMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAutomation1.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("ShelfNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Fyodor Dostoyevski",
                            AverageRating = 0m,
                            Category = "Edebiyat",
                            Description = "Dostoyevski'nin ünlü psikolojik roman eseri.",
                            Genre = "Klasik Edebiyat",
                            ISBN = "978-0-14-044913-6",
                            IsAvailable = true,
                            PageCount = 671,
                            PublicationYear = 1866,
                            Publisher = "İş Bankası Kültür Yayınları",
                            RatingCount = 0,
                            ShelfNumber = "A-001",
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            AverageRating = 0m,
                            Category = "Bilim Kurgu",
                            Description = "Totaliter bir toplumda geçen distopik roman.",
                            Genre = "Distopya",
                            ISBN = "978-0-452-28423-4",
                            IsAvailable = true,
                            PageCount = 328,
                            PublicationYear = 1949,
                            Publisher = "Can Yayınları",
                            RatingCount = 0,
                            ShelfNumber = "B-015",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Paulo Coelho",
                            AverageRating = 0m,
                            Category = "Felsefe",
                            Description = "Kişisel efsaneyi bulma yolculuğu hakkında felsefi roman.",
                            Genre = "Felsefe",
                            ISBN = "978-0-06-112241-5",
                            IsAvailable = true,
                            PageCount = 163,
                            PublicationYear = 1988,
                            Publisher = "Epsilon Yayınları",
                            RatingCount = 0,
                            ShelfNumber = "C-032",
                            Title = "Simyacı"
                        });
                });

            modelBuilder.Entity("LibraryAutomation1.Models.BookRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("BookId", "MemberId")
                        .IsUnique();

                    b.ToTable("BookRatings");
                });

            modelBuilder.Entity("LibraryAutomation1.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LateFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibraryAutomation1.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul, Türkiye",
                            Email = "ahmet.yilmaz@email.com",
                            FirstName = "Ahmet",
                            IsActive = true,
                            LastName = "Yılmaz",
                            MembershipDate = new DateTime(2025, 6, 21, 13, 36, 26, 485, DateTimeKind.Local).AddTicks(5350),
                            PasswordHash = "AQAAAAEAACcQAAAAEJ...",
                            Phone = "0532-123-4567",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ankara, Türkiye",
                            Email = "ayse.kaya@email.com",
                            FirstName = "Ayşe",
                            IsActive = true,
                            LastName = "Kaya",
                            MembershipDate = new DateTime(2025, 6, 21, 13, 36, 26, 485, DateTimeKind.Local).AddTicks(5369),
                            PasswordHash = "AQAAAAEAACcQAAAAEK...",
                            Phone = "0533-987-6543",
                            Role = 0
                        });
                });

            modelBuilder.Entity("LibraryAutomation1.Models.BookRating", b =>
                {
                    b.HasOne("LibraryAutomation1.Models.Book", "Book")
                        .WithMany("BookRatings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAutomation1.Models.Member", "Member")
                        .WithMany("BookRatings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryAutomation1.Models.Loan", b =>
                {
                    b.HasOne("LibraryAutomation1.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryAutomation1.Models.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryAutomation1.Models.Book", b =>
                {
                    b.Navigation("BookRatings");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LibraryAutomation1.Models.Member", b =>
                {
                    b.Navigation("BookRatings");

                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
